---


  - name: get certonly
    command: certbot  --cert-path {{ cert_path }} --key-path {{ cert_path }} --chain-path {{ cert_path }} --non-interactive --agree-tos -m {{ email }} -d {{ host }} certonly --apache

  - name: create cert_path directory
    file: state=directory path={{ cert_path }}

  - name: download sources
    get_url: url=https://openvpn.net/downloads/openvpn-as-latest-ubuntu18.amd_64.deb dest=/tmp/openvpn.deb

  - name: install deb package
    apt:
        deb: /tmp/openvpn.deb


## Optional ... may cause issue, but run again and it should be okay
  - name: back up old cert
    command: /usr/local/openvpn_as/scripts/sacli --import GetActiveWebCerts

  - name: install private key
    command:  /usr/local/openvpn_as/scripts/sacli --key "cs.priv_key" --value_file "/etc/letsencrypt/live/{{ host }}/privkey.pem" ConfigPut

  - name: install private cert
    command:  /usr/local/openvpn_as/scripts/sacli --key "cs.cert" --value_file "/etc/letsencrypt/live/{{ host }}/cert.pem" ConfigPut

  - name: install private chain
    command:  /usr/local/openvpn_as/scripts/sacli --key "cs.ca_bundle" --value_file "/etc/letsencrypt/live/{{ host }}/chain.pem" ConfigPut

  - name: Refresh openvpn with new ssl key
    command: /usr/local/openvpn_as/scripts/sacli start
